"""Analysis endpoints — run analysis, get results."""

import json

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user
from app.core.database import get_db
from app.models.analysis import Analysis
from app.models.dataset import Dataset
from app.models.user import User

router = APIRouter(prefix="/analysis", tags=["analysis"])


class RunAnalysisRequest(BaseModel):
    dataset_id: str
    analysis_type: str = "overview"  # overview | segment | channel | custom
    prompt: str | None = None


class AnalysisResponse(BaseModel):
    id: str
    title: str
    analysis_type: str
    status: str
    result_json: str | None = None
    ai_insights: str | None = None
    chart_configs: str | None = None

    model_config = {"from_attributes": True}


@router.post("/run", response_model=AnalysisResponse, status_code=status.HTTP_201_CREATED)
async def run_analysis(
    body: RunAnalysisRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    # Verify dataset
    result = await db.execute(
        select(Dataset).where(Dataset.id == body.dataset_id, Dataset.owner_id == current_user.id)
    )
    dataset = result.scalar_one_or_none()
    if not dataset:
        raise HTTPException(status_code=404, detail="Dataset not found")

    # Create analysis (placeholder result – real pipeline will use LangGraph)
    analysis = Analysis(
        owner_id=current_user.id,
        dataset_id=dataset.id,
        title=f"{body.analysis_type.title()} Analysis — {dataset.name}",
        analysis_type=body.analysis_type,
        status="completed",
        result_json=json.dumps({"status": "placeholder", "type": body.analysis_type}),
        ai_insights="AI insights will be generated by the lifecycle engine.",
        chart_configs=json.dumps([
            {"type": "area", "title": "Revenue Trend", "dataKey": "revenue"},
            {"type": "bar", "title": "Top Segments", "dataKey": "value"},
        ]),
    )
    db.add(analysis)
    await db.commit()
    await db.refresh(analysis)

    return analysis


@router.get("/", response_model=list[AnalysisResponse])
async def list_analyses(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    result = await db.execute(
        select(Analysis)
        .where(Analysis.owner_id == current_user.id)
        .order_by(Analysis.created_at.desc())
    )
    return result.scalars().all()


@router.get("/{analysis_id}", response_model=AnalysisResponse)
async def get_analysis(
    analysis_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    result = await db.execute(
        select(Analysis).where(Analysis.id == analysis_id, Analysis.owner_id == current_user.id)
    )
    analysis = result.scalar_one_or_none()
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")
    return analysis
